// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var authString;
    authString = 'Basic ' + window.btoa('admin:a');
    $.ajax({
      type: 'POST',
      url: 'API/login',
      headers: {
        'Authorization': authString
      },
      async: false,
      success: function() {
        return console.log('Successfully logged in!');
      }
    });
    return $.ajax({
      type: 'PUT',
      url: 'API/login',
      data: 'test',
      async: false,
      success: function() {
        return console.log('Successfully set the project!');
      }
    });
  });

}).call(this);
