// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $('.form-signin').on('submit', function() {
      var auth, authString;
      auth = "" + ($('#username').val()) + ":" + ($('#password').val());
      authString = 'Basic ' + window.btoa(auth);
      $.ajax({
        type: 'POST',
        url: 'API/login',
        headers: {
          'Authorization': authString
        },
        async: false,
        error: function() {
          $('#badPassAlert').css({
            display: 'block'
          });
          return $('#badPassAlert').html('Error: Invalid Details Provided!');
        }
      });
      $.ajax({
        type: 'PUT',
        url: 'API/login',
        data: $('#project').val(),
        async: false,
        error: function() {
          return console.log('Error setting project!');
        },
        success: function() {
          var queryString, url;
          url = "" + window.location.protocol + "//" + window.location.hostname;
          if (window.location.port) {
            url += ":" + window.location.port;
          }
          url += "/WPISuite/planningpoker.html?username=" + ($('#username').val());
          queryString = window.location.search.split('=');
          if (queryString.length > 1) {
            url += "&session=" + queryString[1];
          }
          return window.location = url;
        }
      });
      return false;
    });
  });

}).call(this);
